### ISSUE TITLE
暗影骑士4 9300h版本的可以用这个efi吗？

### ISSUE THREAD

**Issue by code00000001** [Chakid/Acer-VX15-Hackintosh#2]

**Comment by chakid** [comment]
应该是不可以的，暗影精灵的远景论坛有很多，你可以去上面看看

**Comment by code00000001** [comment]
> 应该是不可以的，暗影精灵的远景论坛有很多，你可以去上面看看
我写错了，是宏碁的暗影骑士4，不是惠普的暗影精灵。暗影骑士4可以用嘛？ 特别是那个数字小键盘能驱动吗？

**Comment by chakid** [comment]
应该是不行的，主板不一样，不过你可以试试，键盘应该比较好驱动

**Comment by chakid** [comment]
键盘驱动一般都是万能的，https://github.com/chakid/Acer-VX15-Hackintosh/tree/master/EFI/CLOVER/kexts/Other/VoodooPS2Controller_v1.9.2.kext 这个就是键盘驱动的位置

**Comment by zhangquanwei962** [comment]
@chakid  YOU CAN TRY THIS : https://gitee.com/zhang966/Acer-VX15-Hackintosh
